version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - TOKENIZERS_PARALLELISM=false
    volumes:
      - .:/app